sudo: false
language: python

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36-django22
    - python: "3.7"
      env: TOXENV=py37-django22
    - python: "3.8"
      env: TOXENV=py38-django22

    # Pypy
    - python: "pypy3"
      env: TOXENV=pypy3-django22

    # Linting
    - python: "3.6"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
